//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OInv.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public  class Model
    {
    
        public int ModelId { get; set; }
        public string ModelSKU { get; set; }
        public Nullable<int> ModelTypeId { get; set; }
        public ProductType ModelType { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ModelSubTypeId { get; set; }
        public ProductSubType ModelSubType { get; set; }
        public Nullable<int> ModelManufaturerId { get; set; }
        public Manufature ModelManufaturer { get; set; }


    }
}
