//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OInv.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public  class Model
    {
    
        public int ModelId { get; set; }
        public string ModelSKU { get; set; }
        public Nullable<int> ModelType { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ModelSubType { get; set; }
        public Nullable<int> ModelManufaturer { get; set; }
    
    }
}
