//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OInv.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public  class ProductSubType
    {
        public int ProductSubTypeId { get; set; }
        public string ProductSubTypeName { get; set; }
        public int ProductSubTypeMainType { get; set; }
    
    }
}
