//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OInv.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public  class Product
    {
    
        public int ProductId { get; set; }
        public Nullable<System.DateTime> ProductDateCreated { get; set; }
        public Nullable<int> ProductSupplier { get; set; }
        public Nullable<int> ProductWarrantyPeriod { get; set; }
        public Nullable<int> ProductModelId { get; set; }
        public string ProductCurrentLoc { get; set; }
        public string OS { get; set; }
        public string OSType { get; set; }
        public string OfficeVersion { get; set; }
        public string BattaryState { get; set; }
        public string IsLicense { get; set; }
    
    }
}
