//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OInv.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    public  class Supplier
    {
        public int SupplierId { get; set; }
        public string SuppliersName { get; set; }
        public Nullable<System.DateTime> SuppliersJoinedDate { get; set; }
        public Nullable<bool> SuppliersIsActive { get; set; }
    
    }
}
