//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIvn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Location_Id { get; set; }
        public string Location_Code { get; set; }
        public string Location_Description { get; set; }
    
        public virtual LocationChange LocationChange { get; set; }
    }
}
