//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIvn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationChange
    {
        public Nullable<int> LocChng_ProductId { get; set; }
        public Nullable<int> LocChng_LocationId { get; set; }
        public Nullable<System.DateTime> LocChng_ChangedDate { get; set; }
        public int LocChng_Id { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Product Product { get; set; }
    }
}
