//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIvn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Notes = new HashSet<Note>();
            this.LocationChanges = new HashSet<LocationChange>();
        }
    
        public int Product_Id { get; set; }
        public Nullable<System.DateTime> ProductDate_Created { get; set; }
        public Nullable<int> Product_Supplier { get; set; }
        public Nullable<int> Product_WarrantyPeriod { get; set; }
        public Nullable<int> Product_ModelId { get; set; }
        public string Product_CurrentLoc { get; set; }
        public string OS { get; set; }
        public string OSType { get; set; }
        public string OfficeVersion { get; set; }
        public string BattaryState { get; set; }
        public string IsLicense { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationChange> LocationChanges { get; set; }
    }
}
