//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIvn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubType
    {
        public int ProductSubType_Id { get; set; }
        public string ProductSubType_Name { get; set; }
        public int ProductSubType_MainType { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
